### ISSUE TITLE
[BUG] The modal dialog window title bar stings doesn't loaded

### ISSUE THREAD

**Issue by GID0317** [mikeli0623/star-rail-warp-sim#107]
![image](https://github.com/user-attachments/assets/0adb830c-3b37-415e-a891-6fbd44f23798)

**Comment by GID0317** [comment]
![image](https://github.com/user-attachments/assets/85f0e21c-e698-4613-82c2-64dc9c821ac1)

seems like the bug appears on both Jing yuan banner

**Comment by mikeli0623** [comment]
Fixed in latest branch
