### ISSUE TITLE
Future banner?

### ISSUE THREAD

**Issue by yeci226** [mikeli0623/star-rail-warp-sim#55]
btw i want to know how to get future banner warp result image

**Comment by mikeli0623** [comment]
What do you mean by this?

**Comment by yeci226** [comment]
> What do you mean by this?

for example
https://raw.githubusercontent.com/mikeli0623/star-rail-warp-sim/main/public/assets/warp-results/dan-heng.webp

**Comment by yeci226** [comment]
![image](https://github.com/mikeli0623/star-rail-warp-sim/assets/88837499/de079f76-e051-48ec-b0b0-980ece7d723f)

and imbibitor-lunae cant be display

**Comment by mikeli0623** [comment]
Yea I forgot to add those. I'll add them at the end of the day.

**Comment by mikeli0623** [comment]
Pushed fix that adds the image.

**Comment by yeci226** [comment]
> What do you mean by this?

i mean is there new character warp image? like jingliu or topaz
btw theres no lynx's image

**Comment by mikeli0623** [comment]
Yea I'll add them with the next update. I'll fix the Lynx thing today.
